openhwgroup/core-v-xif

docs/source/intro.rst
docs/source/x_ext.rst

Fixed broken links and added subsections

---

docs/source/x_ext.rst

Incorporated feedback and corrections from x-if meeting

---

docs/source/x_ext.rst

Signal name updates according to initial reference implementation

---

docs/source/x_ext.rst

Signed-off-by: Oystein Knauserud <Oystein.Knauserud@silabs.com>

Added paragraph about timing.

---

docs/source/x_ext.rst

Fixes for #14, #26,  #27 and #28

---

docs/source/x_ext.rst

Fix for issues #29 and #30

---

docs/source/x_ext.rst

Fix type and description of result we signal

---

docs/source/x_ext.rst

Fixes for #37, #38, #33, #20, #41

---

docs/source/x_ext.rst

XIF spec clarifications

---

docs/source/x_ext.rst

Added missing dbg signal to result interface

---

.github/release.yml
README.md
docs/requirements.txt
docs/source/conf.py
docs/source/index.rst
docs/source/preface.rst

Addition of changelog

---

docs/source/x_ext.rst

X_MISA clarification. Typo fix.

---

docs/source/x_ext.rst

Added requirements to prevent system level deadlock

---

docs/source/x_ext.rst

Fixes according to feedback on PR 52

---

docs/source/x_ext.rst

Redefined behavior when reading writing X0, X1 pair so that it matches the curren RISC-V P extension specification.

Redefined dual read/write behavior inline with RISC-V P extension

---

docs/source/x_ext.rst

Fix for #55, #58 and #59

---

docs/source/x_ext.rst

This is a little request for comments. 
I felt it would make sense to introduce some type definitions to reduce the amount of duplication in the specification. Especially for more complex definitions like the registerflags, this allows good reuse without having to define it over and over. Seemed a better solution to me over the previously defined derived parameter.
This adds hyperlinks where the types are used that take you to the type definition.

Added type definitions for signal types that are used multiple times

---

docs/source/x_ext.rst

... to be unique in flight, incremental wrapping, non-continuous

Tweaking requirements around IDs

---

docs/source/x_ext.rst

- This change is intended to be compatible to the previous definition
- It adds an option for processors with deeper pipelines to signal the register values in a later pipeline stage than the issue handshake
- This reduces the register file accesses
- This can improve performance by allowing register operands to be supplied out of order

Added dedicated register interface

---

docs/source/_static/css/custom.css
docs/source/conf.py
docs/source/x_ext.rst

readability is greatly improved

Preventing horizontal scrollbar on tables

---

docs/source/x_ext.rst

- Making use of that type in issue_resp and result signals
- Specifying that issue_resp.writeback and result.we must be the same for one instruction

Adding a type definition for a register write bit vector

---

docs/source/x_ext.rst

This is an attempt at making the memory interface an optional component controlled with the only directive.
Use
``make SPHINXOPTS="-t MemoryIf" html``
to build with memory interface included.

Making memory interface optional based on MemoryIf tag

---

docs/source/intro.rst

@zarubaf can you check I wrote the right things about CVA6 and Snitch?

add some historical data

---

docs/source/x_ext.rst

@flegert : Please check if this is fine for you

Improving description of id increments to be less ambiguous

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/task.yml

- this is redudant with the better built-in feature of github

Removing associated PRs field from issue templates
